### ISSUE TITLE
pythonclient container cannot start for "kazoo.exceptions.NoNodeError"

### ISSUE THREAD

**Issue by zhaowei7146** [JoeCao/dubbo_jsonrpc_example#1]
After execute "docker-compose up"，dubboadmin/zookeeper/dubboserver containers can normally start up，while pythonclient container failed to start for  "kazoo.exceptions.NoNodeError"，error logs：
# docker logs b0840ad87b7b
Traceback (most recent call last):
  File "client.py", line 20, in <module>
    user_provider = DubboClient(service_interface, registry, version='2.0')
  File "/usr/local/lib/python2.7/site-packages/dubbo_client/rpclib.py", line 34, in __init__
    self.registry.subscribe(interface)
  File "/usr/local/lib/python2.7/site-packages/dubbo_client/registry.py", line 203, in subscribe
    watch=self.event_listener)
  File "/usr/local/lib/python2.7/site-packages/kazoo/client.py", line 1129, in get_children
    include_data=include_data).get()
  File "/usr/local/lib/python2.7/site-packages/kazoo/handlers/utils.py", line 81, in get
    raise self._exception
kazoo.exceptions.NoNodeError

**Comment by zhaowei7146** [comment]
I found the reason for this issue is that zookeeper registry url not totally modified.
